--SELECT * FROM Groups;
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'ИВТ-21-2б','IVT-21-2b')
--delete from Groups where id = 1006;
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'РИС-20-2б','RIS-20-2b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'РИС-22-1б','RIS-22-1b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'РИС-22-2б','RIS-22-2b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'ИВТ-22-1б','IVT-22-1b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'ИВТ-22-2б','IVT-22-2b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КЗИ-19-1б','KZI-19-1b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КЗИ-20-1б','KZI-20-1b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КЗИ-22-1б','KZI-22-1b')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КОБ-18-1с','KOB-18-1s')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КОБ-21-1с','KOB-21-1s')
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'КОБ-22-1с','KOB-22-1s')
SELECT * FROM Groups;