--SELECT * FROM Groups;
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'ИВТ-21-2б','IVT-21-2')
--delete from Groups where id = 1005;
--Insert into Groups(groupNameRU, groupNameENG) values 
--(N'ИВТ-21-1б','IVT-21-1b')
--SELECT * FROM Groups;